### PR TITLE
Fix GetTimelineHashtag

### PR DESCRIPTION
**Pull request by 178inaba**
* Add argument to return hashtag of local timeline.
* Fix bug that slash can not be escaped and it becomes HTTP status 404.
https://play.golang.org/p/YbZqgb7sYK

### CODE REVIEW

**Comment by 178inaba** [comment]
OK!
I will do it today!

**Comment by 178inaba** [comment]
Completed!

However, I have to write a streaming API test.
Since this takes time, I will do it later and issue another PR.

**Comment by mattn** [comment]
Thank you. I thought the changes will not be large such as... Sorry!

**Comment by 178inaba** [comment]
No problem!

Also made the following modifications to the streaming API.

* Fix to send hashtag with GET query.
* User name was given when requesting user streaming, but deleted because it was unnecessary.
* A new request structure was created at reconnection, but it was modified to make it once.

**Comment by mattn** [comment]
>User name was given when requesting user streaming, but deleted because it was unnecessary.

This seems change behavior. Stream timeline remove reblogs.

**Comment by mattn** [comment]
Sorry, it seems my bad. was confusing or maybe I couldn't sleep last night.

**Pull request merged**
