### PR TITLE
Remove needless slash

### PR DESCRIPTION
**Pull request by 178inaba**
Since the path of URL is properly connected using Join, the slash is unnecessary.

The command used for edited is below.

```console
$ find . -name '*.go' ! -name '*test*' | LC_ALL=C xargs sed -i '' 's|/api|api|g'
```

### CODE REVIEW

**Comment by mattn** [comment]
This is intended. Then user specify Server as `http://example.com` (without last slash), url#Path will be empty string. `path.Join("", "bar/baz")` become `bar/baz`

**Comment by 178inaba** [comment]
I think that it will work normally even in that case.

```go
package main

import (
	"fmt"
	"log"
	"net/url"
	"path"
)

func main() {
	p := path.Join("", "bar/baz")

	u, err := url.Parse("http://example.com")
	if err != nil {
		log.Fatal(err)
	}
	u.Path = path.Join(u.Path, p)

	fmt.Println(u.String())
	// Output: http://example.com/bar/baz
}
```
https://play.golang.org/p/Vso_6kuLYP

**Comment by mattn** [comment]
Thanks your explaining. :+1:  I understand this behavior. I'm thinking, when the contributor read this code, he/she may be confusing as WHAT IS THIS STRING. If this removing first slash affect to the worth performance, I will fix this. But if not, I want to keep this.

**Comment by 178inaba** [comment]
There was no difference in performance.

```go
func Slash() string {
	p := path.Join("", "/bar/baz")

	u, err := url.Parse("http://example.com")
	if err != nil {
		log.Fatal(err)
	}
	u.Path = path.Join(u.Path, p)

	return u.String()
}

func RemoveSlash() string {
	p := path.Join("", "bar/baz")

	u, err := url.Parse("http://example.com")
	if err != nil {
		log.Fatal(err)
	}
	u.Path = path.Join(u.Path, p)

	return u.String()
}
```

```console
$ go test -bench .
BenchmarkSlash-8         	 2000000	       640 ns/op
BenchmarkRemoveSlash-8   	 2000000	       643 ns/op
$ go test -bench .
BenchmarkSlash-8         	 2000000	       652 ns/op
BenchmarkRemoveSlash-8   	 2000000	       644 ns/op
```

I close this PR.
Thank you so much for review!

**Pull request closed without merging**
