### PR TITLE
Add Emojis to Status

### PR DESCRIPTION
**Pull request by utam0k**
tootsuite/mastodon#4988

### CODE REVIEW

**Comment by mattn** [comment]
As far as I can see, CustomEmoji seems have shortcode but static_url and url doesn't.

**Comment by utam0k** [comment]
CustomEmojiSerializer serialize shortcode, static_url and url.
CustomEmoji is a feature introduced version 2.0.

https://github.com/tootsuite/mastodon/blob/v2.0.0/app/serializers/rest/custom_emoji_serializer.rb#L6

**Comment by mattn** [comment]
I found it now. BTW, do you want to write test code? I don't mind if you don't to do.

**Comment by utam0k** [comment]
CustomEmoji is parsing on the Mastodon server and it is difficult to test.
I usually do not write golang so I do not know how to write.

**Comment by mattn** [comment]
Okay, will do. Thank you.

2017/10/26 午後2:18 "utam0k" <notifications@github.com>:

**Comment by mattn** [comment]
merged https://github.com/mattn/go-mastodon/commit/1d165763fae1f4f6dc22f78c321b47d51bfec76b

**Pull request closed without merging**
