### PR TITLE
Add a application registration

### PR DESCRIPTION
**Pull request by 178inaba**
This PR provides application registration function.
https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#apps

Usage.

```go
func main() {
	ac := mastodon.NewAppClient(&mastodon.AppConfig{
		Server:       "https://mstdn.jp",
		ClientName:   "Test App",
		RedirectURIs: "urn:ietf:wg:oauth:2.0:oob",
	})

	app, err := ac.RegistrationApp()
	if err != nil {
		log.Fatal(err)
	}

	c := mastodon.NewClient(&mastodon.Config{
		Server:       "https://mstdn.jp",
		ClientID:     app.ClientID,
		ClientSecret: app.ClientSecret,
	})

	...
}
```

### CODE REVIEW

**Comment by mattn** [comment]
No need to make instance like appClient. Please make simple func like below.

```
func RegisterApp() (*Application, error) {
  //
}
```

**Comment by mattn** [comment]
LGTM.

**Comment by mattn** [comment]
Thank you

**Comment by 178inaba** [comment]
Thank you so much for review!
I Fixed it to a simple function.

I was wondering where to place http.Client, but I put it in AppConfig.
Is this OK?

```go
type AppConfig struct {
	http.Client
```

Usage.

```go
func main() {
	app, err := mastodon.RegisterApp(&mastodon.AppConfig{
		Server:       "https://mstdn.jp",
		ClientName:   "Test App",
		RedirectURIs: "urn:ietf:wg:oauth:2.0:oob",
	})
	if err != nil {
		log.Fatal(err)
	}

	c := mastodon.NewClient(&mastodon.Config{
		Server:       "https://mstdn.jp",
		ClientID:     app.ClientID,
		ClientSecret: app.ClientSecret,
	})

	...
}
```

**Comment by 178inaba** [comment]
Thank you so much for merging!

**Comment by mattn** [comment]
> I was wondering where to place http.Client, but I put it in AppConfig.
> Is this OK?

This is my expected.

**Pull request merged**
