### PR TITLE
Add list API support.

### PR DESCRIPTION
**Pull request by BenLubar**
I did not add tests in this pull request.

### CODE REVIEW

**Comment by mattn** [comment]
Thank you. Please add tests

**Comment by BenLubar** [comment]
The tests seem to just be testing the `encoding/json` package. Is this correct, or am I missing something?

**Comment by mattn** [comment]
Yes, this is guard for not breaking current behavior.

**Comment by muesli** [comment]
@BenLubar Nice, I was just looking into adding support for lists myself! Looking forward to this PR getting merged!

**Comment by BenLubar** [comment]
@muesli I've been a bit busy recently, so if you want to take ownership of this PR and write the tests, feel free

**Comment by muesli** [comment]
@BenLubar Ok, will do! I'll just open a separate pull request in that case, unless you want to give me permissions to push to your fork. But I guess that's not worth it.

**Comment by mattn** [comment]
Closed by #93

**Pull request closed without merging**
